# see https://travis-ci.community/t/older-perl-version-stopped-working/4294
dist: trusty
language: perl
perl:
  - "5.28"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"


install:
   - cpanm --quiet --notest Dist::Zilla
   - "dzil authordeps --missing | cpanm --notest "
   - "dzil listdeps --missing | cpanm --notest "

script:
  - dzil smoke --release --author
